### ISSUE TITLE
html-include not working on iOS browsers

### ISSUE THREAD

**Issue by zakrowling** [chris-l/html-include#5]
Hey Chris,
Firstly, thanks so much for building html-include. It's been a lifesaver for a prototype I'm working on.
I just wanted to see if there is way for html-include to work on iOS Safari. Is this an issue with Web Components and iOS?
Thanks,
Zak

**Comment by chris-l** [comment]
I have no idea; I don't own an iphone.

But, something you can check is if you are able to use other web components. If you can't then maybe iOS (or at least, the version you are using) is not compatible with web components.

Sorry, I can't help you. But if it doesn't work and you make a patch to support iOS (and it does not break the support of other browsers), you can make a pull request and I'll include it.
